# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://javed.cn
date_format: "ordinal"
title: Javed
subtitle: "开源是一种美德"
description: "开源是一种美德"
keywords: 开源,Javed
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/javedwang/javedwang.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Javed
organization: HelloWorld, Inc.
organization_url: #
location: Beijing, China
email: i@javed.cn

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /open-source/
    label: 开源

  -
    href: http://weibo.com/javedwang
    label: 微博

  -
    href: /bookmark/
    label: 书签

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: JavedWang


# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [PHP, C++, Python, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
